/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wiki_parser;

import com.memetix.mst.language.Language;
import com.memetix.mst.translate.Translate;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import static java.lang.Math.min;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author akashyadav
 */
public class Wiki_Translation_Tool extends javax.swing.JFrame {

    /**
     * Creates new form Wiki_Translation_Tool
     */
    public String html1;
    public String p = "", z = "", x = "", c = "";
    public int l, i = 0,flag=0,n;
    public int[] heading= new int [100];
    public int[] para= new int [50];
    public int[] list= new int [500];
    public int[] a= new int[300];
    DefaultListModel dList = new DefaultListModel();
    DefaultListModel dHeading= new DefaultListModel();
    DefaultListModel dPara = new DefaultListModel();
    
    public Wiki_Translation_Tool() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 35, 186, -1));

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 76, 186, 310));

        jLabel1.setText("Enter URL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 15, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 220, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 220, -1));

        jList1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane4.setViewportView(jList1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 90, 90));

        jList2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane5.setViewportView(jList2);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 90, 83));

        jList3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane6.setViewportView(jList3);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 90, 79));

        jLabel2.setText("Paragraphs");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        jLabel3.setText("Headings");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jLabel4.setText("Lists");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel5.setText("Translate the below text");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel6.setText("Workspace");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jButton2.setText("Translate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jButton3.setText("Add to Source code");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jButton4.setText("Select");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jButton5.setText("Select");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        jButton6.setText("Select");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        jButton7.setText("Diplay");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Charset charset = StandardCharsets.UTF_8;
        Translate.setClientId("123pankaj");
        Translate.setClientSecret("qwertyuiopasdfghjklzxcvbnm");
        try {
            jTextArea2.setText(Translate.execute(z, Language.ENGLISH, Language.HINDI));
        } catch (Exception ex) {
            Logger.getLogger(Wiki_Translation_Tool.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String s = jTextField1.getText();
        URL website = null;
        try {
            website = new URL(s);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Wiki_Translation_Tool.class.getName()).log(Level.SEVERE, null, ex);
        }
        URLConnection connection = null;
        try {
            connection = website.openConnection();
        } catch (IOException ex) {
            Logger.getLogger(Wiki_Translation_Tool.class.getName()).log(Level.SEVERE, null, ex);
        }
        StringBuilder response = null;
        try (BufferedReader in = new BufferedReader(
                new InputStreamReader(
                        connection.getInputStream()))) {
                    response = new StringBuilder();
                    String inputLine;
                    while ((inputLine = in.readLine()) != null) {
                        response.append(inputLine);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Wiki_Translation_Tool.class.getName()).log(Level.SEVERE, null, ex);
                }

                html1 = response.toString();

                jEditorPane1.setEditable(false);

                jEditorPane1.setContentType("text/html");
                jEditorPane1.setText(html1);

                l = html1.length();
                
                i=0;
                para[0]=0;para[1]=1;
                list[0]=0;list[1]=1;
                heading[0]=0;heading[1]=1;
                int j=1,k=1,m=1;
                do
                {
                    para[j]=html1.indexOf("<p>",para[j-1]+1);
                    j++;
                }
                while(para[j-1]<l-1&&para[j-1]>para[j-2]);
                
                do
                {
                    list[k]=min(html1.indexOf("<li ",list[k-1]+1),html1.indexOf("<li>",list[k-1]+1));
                    k++;
                }
                while(list[k-1]<l-1&&list[k-1]>list[k-2]);
                
                do
                {
                    heading[m]=min(min(html1.indexOf("<h1",heading[m-1]+1),html1.indexOf("<h2",heading[m-1]+1)),html1.indexOf("<h3",heading[m-1]+1));
                    m++;
                }
                while(heading[m-1]<l-1&&heading[m-1]>heading[m-2]);
                
               
                for(i=1;i<j;i++)
                {
                    dPara.addElement("Para"+i);
                }
                jList1.setModel(dPara);
                
                for(i=1;i<k+1;i++)
                {
                    dList.addElement("List"+i);
                }
                jList3.setModel(dList);
                
                for(i=1;i<m+1;i++)
                {
                    dHeading.addElement("Heading"+i);
                }
                jList2.setModel(dHeading);
                
                i = 0;
                while (i < l) {
                    if (html1.charAt(i) == '<') {
                        while (html1.charAt(i) != '>') {
                            p = p + html1.charAt(i);
                            i++;
                        }
                        p = p + html1.charAt(i);
                        i++;
                    } else {
                        break;
                    }
                }

                while (i < l && html1.charAt(i) != '<') {
                    z = z + html1.charAt(i);
                    i++;
                }
                jTextArea1.setText(z);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if(flag==0)
        {
            p = p + jTextArea2.getText();
        while (i < l) {
            if (html1.charAt(i) == '<' && !(html1.charAt(i + 1) == 's' && html1.charAt(i + 2) == 't') && !(html1.charAt(i + 1) == 's' && html1.charAt(i + 2) == 'c')) {
                while (html1.charAt(i) != '>') {
                    p = p + html1.charAt(i);
                    i++;
                }
                p = p + html1.charAt(i);
                i++;
            } else {
                if ((html1.charAt(i) == ' ' && html1.charAt(i + 1) == ' ') || html1.charAt(i) == '\0' || html1.charAt(i) == '\t') {
                    while (i < l && html1.charAt(i) != '<') {
                        p = p + html1.charAt(i);
                        i++;
                    }
                } else {
                    if (html1.charAt(i) == '<' && html1.charAt(i + 1) == 's') {
                        while (html1.charAt(i) != '<' || html1.charAt(i + 1) != '/') {
                            p = p + html1.charAt(i);
                            i++;
                        }
                        while (html1.charAt(i) != '>') {
                            p = p + html1.charAt(i);
                            i++;
                        }
                        p = p + html1.charAt(i);
                        i++;
                    } else {
                        break;
                    }
                }
            }

        }
        z = "";

        while (i < l && html1.charAt(i) != '<') {
            z = z + html1.charAt(i);
            i++;
        }

        jTextArea1.setText(z);
        }
             
        if(flag==2)
        {
            flag=0;
            jTextArea1.setText(z);
        }
        
        if(flag==1)
        {
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        n=jList1.getSelectedIndex();
        n=para[n+1];
        if(n<i)
        {
            jTextArea1.setText("This field is either being translated or has been translated before");
        }
        else
        {
        flag=1;
        while(true)
        {
            if(html1.charAt(n)=='<'&&html1.charAt(n+1)!='/')
            {
                while(html1.charAt(n)!='>')
                    n++;
                n++;
            }
            else
                break;
        }
        if(html1.charAt(n)=='<'&&html1.charAt(n+1)=='/')
        {
            jTextArea1.setText("There is no text to translate");
            flag=2;
        }
        else
        {
            z="";
            while(html1.charAt(n)!='<')
            {
                z=z+html1.charAt(n);
                n++;
            }
            jTextArea1.setText(z);
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wiki_Translation_Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wiki_Translation_Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wiki_Translation_Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wiki_Translation_Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wiki_Translation_Tool().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
